- name: Test SSH Connection
  env:
    CPANEL_USERNAME: ${{ secrets.CPANEL_USERNAME }}
    CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
  run: |
    ssh -vvv -i ~/.ssh/id_rsa $CPANEL_USERNAME@$CPANEL_HOST "echo 'SSH connection successful'"
